### ISSUE TITLE
Computing products of the form `inv(A) * B * C = Bidiagonal`

### ISSUE THREAD

**Issue by DanielVandH** [JuliaLinearAlgebra/InfiniteLinearAlgebra.jl#185]
This issue is about what we discussed @dlfivefifty. I'll use this to track development on this / refer to if I eventually get onto a PR. Also want to be sure this isn't way too specific that it might not be suited for this package, but I think it should be fine.

It would be useful to have a type for efficiently representing $\mathbf X = \mathbf A^{-1}\mathbf B \mathbf C$, where $\mathbf A$ and $\mathbf C$ are either both upper Hessenberg or both upper triangular and $\mathbf B$ is banded so that $\mathbf X$ is bidiagonal. Something like

```julia
@concrete struct BidiagonalTransform{T} <: LazyMatrix{T} # need a different name, one that isn't bad/wrong
    A
    B
    C
    X
end
```
with `X` a finite bidiagonal matrix that grows on demand.

**Comment by dlfivefifty** [comment]
One option which is similar to what @TSGut and I did before is only store the bands, not the whole matrix, which is then wrapped in a `Bidiagonal`. Which I'd call something like `BidiagonalConjugationData`.

**Comment by TSGut** [comment]
Ideally the implementation would be such that if `A` and `C` are also banded then this would cost $O(n)$ similar to the implementation in `cholesky_jacobimatrix` in ClassicalOPs.jl (albeit there the situation is banded `R`, SymTridiagonal `X`, compute `inv(R)*X*R` which is a good bit less general). If that implementation exists it could simplify (triangular) decomposition based jacobimatrices a good bit.

**Comment by DanielVandH** [comment]
The application in mind was mostly for some derivative matrices. The same ideas could probably be used for the case where product is tridiagonal though, to help with those Jacobi matrices you mention. I almost have a PR ready pretty soon for review.
